### ISSUE TITLE
(5) As a player, I would like to determine the size of my city so that I can customise my playing game experience

### ISSUE THREAD

**Issue by notyumin** [notyumin/SimpCity#20]
- [x] Add option to menu
- [x] Set board size 
- [x] Set building copies

Size range: 4x4 to 7x7
Number of copies of buildings:
- 4x4: 8 per building
- 5x5: 12 per building
- 6x6: 18 per building
- 7x7: 24 per building

**Comment by jolenecpn** [comment]
bug found in initializing row, thus this happened, trying to fix now 
![Screenshot (627)](https://user-images.githubusercontent.com/93184369/150179757-dcc27aad-a801-4a89-829b-3f695e2d4050.png)

**Comment by jolenecpn** [comment]
fixed the bug ._.
