### ISSUE TITLE
(5) As a player, I would like to view an in-game menu when I am playing so that I can see all the in-game actions I can take

### ISSUE THREAD

**Issue by notyumin** [notyumin/SimpCity#4]
- [x] Display Board
- [x] Randomise buildings for first 2 options
- [x] Display options

**Comment by jolenecpn** [comment]
unable to print >4 columns for game board
![Screenshot (617)](https://user-images.githubusercontent.com/93184369/149658757-7463a55c-d502-442a-9068-8771cb0b20d8.png)

**Comment by Harjun751** [comment]
Issue should be fixed as of #31 - do review if it works.

![image](https://user-images.githubusercontent.com/57029562/149664397-ab5e869f-59bf-4b13-9890-f38a1e46250d.png)
![image](https://user-images.githubusercontent.com/57029562/149664401-b6834920-161e-441b-8fa0-7bc2c0122474.png)

**Comment by jolenecpn** [comment]
reviewed, works now, thanks
